name: build-images

on:
  schedule:
    - cron: '0 0 * * 1'
  workflow_dispatch:
  push:

jobs:
  cleanup-images:
    permissions:
      packages: write
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image_name:
          - debian-tools
          - debian-tools-runtime
          - debian-tools-2
          - debian-tools-2-runtime
          - trixie-tools
          - trixie-tools-runtime
    steps:
    - uses: actions/delete-package-versions@v5
      continue-on-error: true
      with:
        package-name: ${{ matrix.image_name }}
        package-type: container
        min-versions-to-keep: 1
        delete-only-untagged-versions: false
        token: ${{ secrets.GITHUB_TOKEN }}
  build:
    permissions:
      contents: read
      packages: write
      id-token: write

    strategy:
      matrix:
        image_name: 
          - debian-tools-2
          - debian-tools-2-runtime
          - trixie-tools
          - trixie-tools-runtime
          #- bookworm-tools
          #- bookworm-tools-runtime
      max-parallel: 1
      fail-fast: true
          
    uses: b521f771d8991e6f1d8e65ae05a8d783/base-tools/.github/workflows/ci.yml@main
    with:
      image_name: ${{ matrix.image_name }}
